### ISSUE TITLE
Cannot install 

### ISSUE THREAD

**Issue by piotrwitek** [casper-ecosystem/cep18#89]
Hi
I'm trying to install the "cep-18" client using the official installation readme guide.
There is an error in the installation script while using "npm i casper-erc20-js-client".

What is your advice here so we can use it properly in the Casper Wallet product?

```js
npm i casper-cep18-js-client
npm ERR! code 1
npm ERR! path /Users/piotrek/Dev/casper-wallet/node_modules/casper-cep18-js-client
npm ERR! command failed
npm ERR! command sh -c -- npm run generate:wasm
npm ERR! > casper-cep18-js-client@1.0.0 generate:wasm
npm ERR! > ts-node "src/scripts/copy-and-convert-wasms.ts"
npm ERR! node:internal/modules/cjs/loader:988
npm ERR!   throw err;
npm ERR!   ^
npm ERR! 
npm ERR! Error: Cannot find module './copy-and-convert-wasms.ts'
npm ERR! Require stack:
npm ERR! - /Users/piotrek/Dev/casper-wallet/node_modules/casper-cep18-js-client/src/scripts/imaginaryUncacheableRequireResolveScript
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
npm ERR!     at Function.resolve (node:internal/modules/cjs/helpers:109:19)
npm ERR!     at requireResolveNonCached (/Users/piotrek/Dev/casper-wallet/node_modules/ts-node/dist/bin.js:549:16)
npm ERR!     at getProjectSearchDir (/Users/piotrek/Dev/casper-wallet/node_modules/ts-node/dist/bin.js:519:40)
npm ERR!     at phase3 (/Users/piotrek/Dev/casper-wallet/node_modules/ts-node/dist/bin.js:267:27)
npm ERR!     at bootstrap (/Users/piotrek/Dev/casper-wallet/node_modules/ts-node/dist/bin.js:47:30)
npm ERR!     at main (/Users/piotrek/Dev/casper-wallet/node_modules/ts-node/dist/bin.js:33:12)
npm ERR!     at Object.<anonymous> (/Users/piotrek/Dev/casper-wallet/node_modules/ts-node/dist/bin.js:579:5)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1155:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     '/Users/piotrek/Dev/casper-wallet/node_modules/casper-cep18-js-client/src/scripts/imaginaryUncacheableRequireResolveScript'
npm ERR!   ]
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/piotrek/.npm/_logs/2023-06-09T13_23_33_383Z-debug-0.log
```

**Comment by darthsiroftardis** [comment]
@gyroflaw @mgibson-casper Could you please look into this

**Comment by gyroflaw** [comment]
> @gyroflaw @mgibson-casper Could you please look into this

this can be fixed by publishing client to npm :)

**Comment by RitaMAllenCA** [comment]
This is an issue with our documentation - we are citing something that does not exist.   We are fixing/updating the documentation as part of our formal release this week.

**Comment by hoffmannjan** [comment]
[here is it described](https://github.com/casper-ecosystem/cep18/tree/master/client-js#development) - @piotrwitek please let us know if it works for you locally

**Comment by hoffmannjan** [comment]
[its described here](https://github.com/casper-ecosystem/cep18/tree/master/client-js#development) - @piotrwitek please let us know if it works for you locally ☺️

**Comment by RitaMAllenCA** [comment]
will be resolved with republishing npm.    @gyroflaw please close once you confirm.

**Comment by piotrwitek** [comment]
Looks good! Thanks, I'll check the local build and try if that works on Monday

**Comment by deuszex** [comment]
Hi @piotrwitek did you manage to get to the build?

**Comment by piotrwitek** [comment]
Hi, yes installation issue is resolved, thanks!
